from __future__ import annotations

import asyncio
import os

import dotenv

dotenv.load_dotenv()

NUM_RUNS_PER_QUESTION = 3
SKIP_PREVIOUSLY_FORECASTED_QUESTIONS = True
METACULUS_MAX_CONCURRENT_REQUESTS = int(os.getenv("METACULUS_MAX_CONCURRENT_REQUESTS", "1"))
METACULUS_API_RATE_LIMITER = asyncio.Semaphore(METACULUS_MAX_CONCURRENT_REQUESTS)
METACULUS_REQUEST_INTERVAL = float(os.getenv("METACULUS_REQUEST_INTERVAL", "3.0"))

METACULUS_TOKEN = os.getenv("METACULUS_TOKEN")
PERPLEXITY_API_KEY = os.getenv("PERPLEXITY_API_KEY")
ASKNEWS_CLIENT_ID = os.getenv("ASKNEWS_CLIENT_ID")
ASKNEWS_SECRET = os.getenv("ASKNEWS_SECRET")
ASKNEWS_API_KEY = os.getenv("ASKNEWS_API_KEY")
EXA_API_KEY = os.getenv("EXA_API_KEY")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
SERPAPI_API_KEY = os.getenv("SERPAPI_API_KEY")
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")
OPENROUTER_COST_HARD_LIMIT_USD = float(os.getenv("OPENROUTER_COST_HARD_LIMIT_USD", "0"))

# Tournament IDs
Q4_2024_AI_BENCHMARKING_ID = 32506
Q1_2025_AI_BENCHMARKING_ID = 32627
FALL_2025_AI_BENCHMARKING_ID = "fall-aib-2025"
SPRING_2026_AI_BENCHMARKING_ID = "spring-aib-2026"
SUMMER_2026_AI_BENCHMARKING_ID = "summer-futureeval-2026"
CURRENT_MINIBENCH_ID = "minibench"

Q4_2024_QUARTERLY_CUP_ID = 3672
Q1_2025_QUARTERLY_CUP_ID = 32630
CURRENT_METACULUS_CUP_ID = "metaculus-cup-summer-2026"

AXC_2025_TOURNAMENT_ID = 32564
AI_2027_TOURNAMENT_ID = "ai-2027"

DEFAULT_TOURNAMENT_ID = CURRENT_METACULUS_CUP_ID

TOURNAMENT_MAPPING = {
    "q4-2024-ai": Q4_2024_AI_BENCHMARKING_ID,
    "q1-2025-ai": Q1_2025_AI_BENCHMARKING_ID,
    "fall-2025-ai": FALL_2025_AI_BENCHMARKING_ID,
    "spring-2026-ai": SPRING_2026_AI_BENCHMARKING_ID,
    "summer-2026-ai": SUMMER_2026_AI_BENCHMARKING_ID,
    "minibench": CURRENT_MINIBENCH_ID,
    "q4-2024-cup": Q4_2024_QUARTERLY_CUP_ID,
    "q1-2025-cup": Q1_2025_QUARTERLY_CUP_ID,
    "metaculus-cup": CURRENT_METACULUS_CUP_ID,
    "axc-2025": AXC_2025_TOURNAMENT_ID,
    "ai-2027": AI_2027_TOURNAMENT_ID,
}

EXAMPLE_QUESTIONS: list[tuple[int, int]] = [
    (578, 578),      # Human Extinction - Binary
    (14333, 14333),  # Age of Oldest Human - Numeric
    (22427, 22427),  # Number of New Leading AI Labs - Multiple Choice
    (38195, 38880),  # Number of US Labor Strikes Due to AI in 2029 - Discrete
]

AUTH_HEADERS = {"Authorization": f"Token {METACULUS_TOKEN}"}
API_BASE_URL = "https://www.metaculus.com/api"
MAX_API_GET_RETRIES = 3
INITIAL_API_GET_RETRY_WAIT_SECONDS = float(os.getenv("INITIAL_API_GET_RETRY_WAIT_SECONDS", "3.0"))

CONCURRENT_REQUESTS_LIMIT = 5
llm_rate_limiter = asyncio.Semaphore(CONCURRENT_REQUESTS_LIMIT)
